### ISSUE TITLE
Need Help how Deploy to heroku

### ISSUE THREAD

**Issue by Ijazweb** [SuspiciousLookingOwl/youtubei#1]
**Is your feature request related to a problem? Please describe.**
Need Help how to Deploy this to heroku

**Comment by SuspiciousLookingOwl** [comment]
Sorry but I have no experience on using Heroku as I never use it before.

This article might be helpful: [Deploying Node.js Apps on Heroku](https://devcenter.heroku.com/articles/deploying-nodejs)

Since this is not really related to the library, I will close this.
