### ISSUE TITLE
Fetch Error 

### ISSUE THREAD

**Issue by jenny4711** [SuspiciousLookingOwl/youtubei#105]
I got this error, Please check it up, and let me know. 
Thank you. 

Error in makeSummary: FetchError: invalid json response body at https://www.google.com/sorry/index?continue=https://www.youtube.com/watch%3FprettyPrint%3Dfalse%26v%3DO_MQr4lHm0c%26pbj%3D1&q=EgQDgW_cGLbDg7MGIjCK6X3jXpmaI27gysCZioJGr81G3CoS9Ziif5yhnm_SLVfpwAYn9dxbKG-5IACPju4yAXJaAUM reason: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    **at /opt/render/project/src/node_modules/youtubei/node_modules/node-fetch/lib/index.js:273:32**
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'invalid-json'

**Comment by SuspiciousLookingOwl** [comment]
Going to close this, it seems like this is a same issue with https://github.com/SuspiciousLookingOwl/youtubei/issues/97
