### ISSUE TITLE
Captions text seems to include timestamps. 

### ISSUE THREAD

**Issue by altr** [SuspiciousLookingOwl/youtubei#109]
**Describe the bug**
Captions text seems to include timestamps. 
Tested with this video: https://www.youtube.com/watch?v=FJOXDCzlGv0

Text that is retrieved 
'I0  wish1600  to4000'
'thank0  the10000  Prime12010  Minister14410'
etc..

**To Reproduce**
```typescript
const youtube = new Client();
const video = await youtube.getVideo("FJOXDCzlGv0");
const captions = await video?.captions.get('en');
``` 

**Expected behavior**
No timestamps in the text.

**Screenshots**
captions object in VSCode
![Screenshot from 2024-06-27 15-13-06](https://github.com/SuspiciousLookingOwl/youtubei/assets/687103/4988519b-e17a-46ac-b224-6c73025f23b8)

Actual text
![Screenshot from 2024-06-27 15-10-52](https://github.com/SuspiciousLookingOwl/youtubei/assets/687103/158ef7e1-ecf7-41c3-bad2-f6b917d08632)

**Additional context**

**Comment by SuspiciousLookingOwl** [comment]
Fix published on `1.5.3` 👍🏻
