### ISSUE TITLE
getVideo and getPlaylist not working while oauth activated

### ISSUE THREAD

**Issue by MaitreGEEK** [SuspiciousLookingOwl/youtubei#123]
**Describe the bug**
When I'm using oauth with a refresh token it seems I can't load any playlists or songs with their ids nor search but without auth it works

**To Reproduce**
Load a client with a refreshtoken

**Expected behavior**
There should have results for songs and playlists

**Code**
Try this if you want with getrefreshtoken a function that returns you a new token each iteration

```js 
async function testClient(client) {
    let testVideo = await client.getVideo("dQw4w9WgXcQ")
    if (!testVideo) return false
    let testPlaylist = await client.getPlaylist("PLpIYdjpi2QX4jU15ProfU8BsjXML-VFrZ")
    if (!testPlaylist) return false

    return true
}

async function generateClient(attempts = 0) {
    const refreshToken = (attempts == 10) ? null : await getRefreshToken();
    let client = new Client({
        oauth: {
            enabled: !!refreshToken,
            refreshToken
        }
    });

    if (!await testClient(client)) {
        return generateClient(attempts + 1)
    }
    else return client
}```

**Comment by MaitreGEEK** [comment]
Same result for new or old account

**Comment by SuspiciousLookingOwl** [comment]
Seems like YouTube has finally disabled OAuth support, check https://github.com/yt-dlp/yt-dlp/issues/11462, there's nothing that I can do unfortunately.
