### ISSUE TITLE
Support for IPv6

### ISSUE THREAD

**Issue by SushiBtw** [SuspiciousLookingOwl/youtubei#14]
**Is your feature request related to a problem? Please describe.**
Not really, maybe ratelimits.

**Describe the solution you'd like**
I suggest adding IPv6 support, if you can't do it for now, I can work on it, as that could help me.

**Additional context**
None

**Comment by SuspiciousLookingOwl** [comment]
Do you mean add support for sending HTTP request using IPv6?

No idea how to correctly do this, if this [answer](https://stackoverflow.com/a/31509474/12397250) is correct, it's just as simple as adding `localAddress`  to the `https` option right?

```js
import https from "https";

https.request({
    localAddress: "ipv6 here"
});
```

**Comment by SushiBtw** [comment]
Correct

**Comment by SuspiciousLookingOwl** [comment]
I will probably just add it to `Client` constructor as an options,
```js
const client = new Client({
    httpOptions: {
        localAddress: "ipv6 here"
    }
});
```

**Comment by SushiBtw** [comment]
And a way to change it to allow multi ipv6 👍

**Comment by SushiBtw** [comment]
Hey, any news on this? Do you need some help?

**Comment by SuspiciousLookingOwl** [comment]
Hi, busy with other stuff recently, don't have time to work on this library. If you want to do a PR, feel free to do so.

**Comment by SushiBtw** [comment]
> Hi, busy with other stuff recently, don't have time to work on this library. If you want to do a PR, feel free to do so.

Hey, should be done in #15

**Comment by SuspiciousLookingOwl** [comment]
Apologize for the delayed response.

This will be available on next update

```js
new Client({
    httpOptions: {
        localAddress: "..."
    }
})
```
