### ISSUE TITLE
Cannot read property '0' of undefined [BUG]

### ISSUE THREAD

**Issue by Mr-Leonerrr** [SuspiciousLookingOwl/youtubei#18]
**Describe the bug**
For some reason I can only play one song, when I try to find another it gives me an error.
The song is `Panini by Lil Nas X`

**Expected behavior**
Search the songs and receive no error.

**Screenshots**
_Error_
![image](https://user-images.githubusercontent.com/56647065/125184944-5e41d600-e1e7-11eb-8c9e-d9c2999b9dc9.png)
_Usage_
![code](https://user-images.githubusercontent.com/56647065/125184984-90533800-e1e7-11eb-816e-e340afb7f13b.png)

**Additional context**
Youtubei Version: [0.0.1-rc.16]
Node.js Version: [14.16.1]
Discord.js Version: [12.3.1]

**Comment by SuspiciousLookingOwl** [comment]
Hi, seems like the latest update (`rc.16`) breaks my library, try downgrading to `rc.15` temporarily while I figure out what causes the issue

`npm i youtubei@0.0.1-rc.15`

**Comment by SuspiciousLookingOwl** [comment]
Try upgrading to `rc.17`, should be fixed.

**Comment by SuspiciousLookingOwl** [comment]
Please upgrade to `0.0.1-rc.18`, should be fixed

**Comment by Mr-Leonerrr** [comment]
> 
> 
> Please upgrade to `0.0.1-rc.18`, should be fixed

Yeah solved, thank you! ^^
