### ISSUE TITLE
[BUG] JSON parse Error

### ISSUE THREAD

**Issue by EvasiveXkiller** [SuspiciousLookingOwl/youtubei#19]
**Describe the bug**
Library wont continue due to parsing error.

```
uncaughtException: Unexpected token < in JSON at position 0
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Gunzip.<anonymous> (C:\Users\Thunderbolt XV\Desktop\soundwave\SoundWave-dev\node_modules\youtubei\dist\common\HTTP.js:75:39)
    at Gunzip.emit (events.js:315:20)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by SuspiciousLookingOwl** [comment]
Please add a reproducible code

**Comment by EvasiveXkiller** [comment]
```
const {Client} = require("youtubei");
const ytLinkResolver = new Client();
let videoDetails = await ytLinkResolver.getVideo(youtube_parser(rawinput)).catch(() => {resolve(false);});
```

Above is a snippet of the code. The link in question is [this](https://www.youtube.com/watch?v=pRfmrE0ToTo)

**Comment by SuspiciousLookingOwl** [comment]
Seems like you are being rate limited, are you on a VPS or using a VPN? If so, try it on a local PC, or without VPN.

**Comment by EvasiveXkiller** [comment]
I think the rate limiting is on, Im usually running the library locally, however i switched to mobile data and it seems to have fixed it.

**Comment by SuspiciousLookingOwl** [comment]
If that's the case then it's a limitation from Youtube and unfortunately there's nothing I can do.
