### ISSUE TITLE
Is it possible to get this running in the browser?

### ISSUE THREAD

**Issue by johtso** [SuspiciousLookingOwl/youtubei#20]
Or is this node only? If so would it be a lot of work to make this usable in a browser context?

**Comment by SuspiciousLookingOwl** [comment]
The library is built for Node only, but I'm pretty you can bundle it using something like webpack so you can use it in browser.

And when you manage to bundle it for browser, you will stumble upon CORS issue, which can be mitigated by [disabling same origin policy on browser](https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome), but you probably don't want that. 

At the end, you still need a server that (at least) serves as a proxy, you can pass `httpOptions` on the `Client`'s constructor, and set the `host` to your proxy server:

```js
const youtube = new Client({
	httpOptions: {
		host: "yourproxyserver.com"
        }
});
```

If you use  nginx as your proxy server, simple configuration like this will be enough
```
server {
	listen 443;
	server_name yourproxyserver.com;

	location / {
		proxy_pass https://www.youtube.com/;
	}
}
 ```
