### ISSUE TITLE
How to use on client side?

### ISSUE THREAD

**Issue by vladikvenger** [SuspiciousLookingOwl/youtubei#21]
got an error when try running on windows nodejs.

c:\xampp\htdocs>node server.js
file:///c:/xampp/htdocs/server.js:3
import { Client } from "youtubei";
         ^^^^^^

SyntaxError: Identifier 'Client' has already been declared
←[90m    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)←[39m
←[90m    at async link (internal/modules/esm/module_job.js:63:21)←[39m

c:\xampp\htdocs>node server.js
file:///c:/xampp/htdocs/server.js:1
const { Client } = require("youtubei");
                   ^

ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and 'c:\xampp\htdocs\package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///c:/xampp/htdocs/server.js:1:20
←[90m    at ModuleJob.run (internal/modules/esm/module_job.js:169:25)←[39m
←[90m    at async Loader.import (internal/modules/esm/loader.js:177:24)←[39m
←[90m    at async Object.loadESM (internal/process/esm_loader.js:68:5)←[39m

How can this actually being used in client server?

**Comment by SuspiciousLookingOwl** [comment]
This library is made for Node only.

Read more here: https://github.com/SuspiciousLookingOwl/youtubei/issues/20#issuecomment-881393450
