### ISSUE TITLE
[BUG] Playlist return undefined

### ISSUE THREAD

**Issue by KagChi** [SuspiciousLookingOwl/youtubei#22]
**Describe the bug**
When i load this playlist `PLVH_c0JJpuSpTf3MI7vqz_6UKwvbbtitk` its return undefined, but if i post using Client#http video content is available

**To Reproduce**
Client.getPlaylist("PLVH_c0JJpuSpTf3MI7vqz_6UKwvbbtitk") 

**Expected behavior**
Should return all videos in playlist.

**Screenshots**
![image](https://media.discordapp.net/attachments/615704542562091028/870338249854418974/Screenshot_2021-07-29-23-13-21-81_572064f74bd5f9fa804b05334aa4f912.jpg)

**Additional context**

**Comment by SuspiciousLookingOwl** [comment]
Thanks for reporting this.

Please update to rc.20, should be fixed
