### ISSUE TITLE
[BUG] Error — "getVideo()" on url "youtu.be"

### ISSUE THREAD

**Issue by Asgarrrr** [SuspiciousLookingOwl/youtubei#30]
**Describe the bug**
Error when using "getVideo()" on url "youtu.be"

**Screenshots**

<img width="574" alt="Capture d’écran 2021-09-26 à 15 01 36" src="https://user-images.githubusercontent.com/36574651/134809163-f5d50ad6-70e8-401f-8c47-a5411df281eb.png">
<img width="564" alt="Capture d’écran 2021-09-26 à 15 00 25" src="https://user-images.githubusercontent.com/36574651/134809126-a4461247-2ee8-44e4-abac-dad53d4c7e4a.png">
<img width="605" alt="Capture d’écran 2021-09-26 à 15 01 03" src="https://user-images.githubusercontent.com/36574651/134809148-87a7e3af-47a7-4bc5-bfd9-8bd736552934.png">

**Comment by SuspiciousLookingOwl** [comment]
Please parse the URL into Video ID on your side and pass it as the parameter value instead of passing the whole URL. I'm planning to drop support for passing URL directly to `.getVideo()` / `.getPlaylist()`.

```js
const videoUrl = "https://youtu.be/aj-XTwwpRas?t=3944";

const url = new URL(videoUrl);
const videoId = url.pathname.substr(1);

client.getVideo(videoId);
```

**Comment by SuspiciousLookingOwl** [comment]
Please parse the URL into Video ID on your side and pass it as the parameter value instead of passing the whole URL. I'm planning to drop support for passing URL directly to `.getVideo()` / `.getPlaylist()`.

```js
const videoUrl = "https://youtu.be/dQw4w9WgXcQ";

const url = new URL(videoUrl);
const videoId = url.pathname.substr(1);

client.getVideo(videoId);
```

**Comment by Asgarrrr** [comment]
Sorry, 

I'm on version 0.0.1-rc.22

<img width="514" alt="Capture d’écran 2021-09-26 à 15 55 28" src="https://user-images.githubusercontent.com/36574651/134810903-86fdecb0-d861-4dd7-aa18-a98377c32a0a.png">

<img width="550" alt="Capture d’écran 2021-09-26 à 15 55 39" src="https://user-images.githubusercontent.com/36574651/134810912-fdce85eb-702e-4ad0-bf13-3f50d72f6aa3.png">

**Comment by Asgarrrr** [comment]
Ok, juste a version problem, sorry
