### ISSUE TITLE
Client#options are missing

### ISSUE THREAD

**Issue by SushiBtw** [SuspiciousLookingOwl/youtubei#36]
**Describe the bug**
Hey, seems you accidently removed the `Client#options` value from the Client class. Is that intended?

**Comment by SuspiciousLookingOwl** [comment]
The options is still there, but I [refactored](https://github.com/SuspiciousLookingOwl/youtubei/commit/d30412a963ab4c2eba4a41e2b80d8b15b06f8298) it, the latest options look like [this](https://youtubei.netlify.app/docs/api/classes/client#clientoptions)

**Comment by SushiBtw** [comment]
Ok, my bad. Thanks.
