### ISSUE TITLE
youtubei Should handle 404 or private videos

### ISSUE THREAD

**Issue by Hazmi35** [SuspiciousLookingOwl/youtubei#37]
**Describe the bug**
`youtubei` Should throw useful error messages or handle 404 / private videos

Currently using `getVideo` with non-existing video for example `https://www.youtube.com/watch?v=not-exists` or a private video
`https://www.youtube.com/watch?v=mSBZvjbf7yM` throws an error (see screenshot)

**To Reproduce**
```js
const { Client } = require("youtubei");

const youtube = new Client();

youtube.getVideo("https://www.youtube.com/watch?v=not-exists"); // throws error
youtube.getVideo("https://www.youtube.com/watch?v=mSBZvjbf7yM"); // also throws errors
```

**Expected behavior**
`youtubei` Should throw useful error messages or just return undefined

**Screenshots**
![image](https://user-images.githubusercontent.com/32807631/137023388-2f704a14-821f-4297-b973-a6e070d4e606.png)

**Additional context**
Hazmi35/jukebox#761

**Comment by SuspiciousLookingOwl** [comment]
I agree that throwing useful error message is better, however it's a bit difficult to cover all possible errors that can be thrown because there are many different cases like this that the lib needs to check. I won't fix this anytime soon.

**Comment by SuspiciousLookingOwl** [comment]
This should be fixed in v1, but if the issue still persists, fill free to reopen the issue.

(Also check the [v1 migration guide](https://github.com/SuspiciousLookingOwl/youtubei/issues/54))
