### ISSUE TITLE
Undefined sub count :(

### ISSUE THREAD

**Issue by supertiger1234** [SuspiciousLookingOwl/youtubei#38]
**Describe the bug**
`item.channel.subscriberCount` `returns undefined` when searching for videos.

**To Reproduce**
```ts
const results = await client.search("Overwatch").then(items => {
    return items.forEach(item => {
        if (item.constructor.name === "VideoCompact") console.log({subCount: item.channel.subscriberCount});
    });
})
console.log(results);
```
        

**Expected behavior**
Show me the sub counts instead of saying "undefined"

**Comment by SuspiciousLookingOwl** [comment]
This is expected, there are no subscriber count data available from the video search result, only id, name, and avatar url)
![image](https://user-images.githubusercontent.com/32597776/139848353-9d81bf6c-4115-4a0e-9de4-9d586e97f492.png)

**Comment by supertiger1234** [comment]
ahh, i see. Thanks!

**Comment by supertiger1234** [comment]
BTW, even when using the `getVideo` function, subcount is still undefined :/

**Comment by SuspiciousLookingOwl** [comment]
Yea somehow I missed that, will be fixed on next version
