### ISSUE TITLE
Issue with getPlaylist returning wrong VideoCompact#channel object

### ISSUE THREAD

**Issue by SushiBtw** [SuspiciousLookingOwl/youtubei#4]
**Describe the bug**
`Playlist` object that contains the` VideoCompact` returned by `getPlaylist()` method shows wrong channel information.

**To Reproduce**
1. Send a request via `getPlaylist()`,
2. Observe the `Playlist#videos` returning wrong `channel` data.

**Expected behavior**
It should return the `Video` channel object, not the `Playlist` channel object.

**Comment by SuspiciousLookingOwl** [comment]
Ah I wasn't aware of that, thanks for reporting!

Fixing this soon.

**Comment by SuspiciousLookingOwl** [comment]
Try upgrade to `@0.0.1-rc.14`, should be fixed 😁
