### ISSUE TITLE
Cannot read property 'continuations' of undefined

### ISSUE THREAD

**Issue by MontiKasta** [SuspiciousLookingOwl/youtubei#41]
**Describe the bug**
An error occurs due to the deficiency in the part of receiving the data of the live broadcasts in the module.

```
this.chatContinuation =
            data[3].response.contents.twoColumnWatchNextResults.conversationBar.liveChatRenderer.continuations[0].reloadContinuationData.continuation;
```

The chat section can be turned off in Youtube live broadcasts. The system gives an error because it cannot receive the chat data.

**To Reproduce**

1. If the chat section is closed, it should be returned as `null`

If the chat section is closed, the response should be like this

```
 watchingCount: 1000,
 chatContinuation: null
```

**Expected behavior**
Data that cannot be received (`chatContinuation`) should be sent as null so that the system does not malfunction. So the system will work better.

**Comment by SuspiciousLookingOwl** [comment]
Thank you for reporting this, should be fixed in `0.0.1-rc.28`
