### ISSUE TITLE
Protobuf Endpoints?

### ISSUE THREAD

**Issue by OskarEichler** [SuspiciousLookingOwl/youtubei#44]
Hey @SuspiciousLookingOwl,

First up - great work on Youtubei! We are currently looking at collecting some data from YouTube's API that seems to only be available via the mobile app at the moment. Did a little man-in-the-middle sniffing to see which requests are being sent, and they definitely all go to youtubei.googleapis.com/youtubei/v1/...

Unfortunately it looks like the content-encoding is different and they are using protobuf for the iOS apps instead of application/json. Do you think it is possible to either find the right .proto schemas for the protocol or convert the requests to json somehow? Please let me know!

All the best,
Oskar

**Comment by LuanRT** [comment]
I've been reverse engineering some of YouTube's private APIs and the tools described in this [article](https://dfir.blog/unfurling-unknown-protobufs/) helped me a lot while decoding protobufs.

Hope it helps!

**Comment by SuspiciousLookingOwl** [comment]
This is probably outside of this lib's scope. The article referred by @LuanRT might help you.
