### ISSUE TITLE
getVideo() method returns undefined for every input

### ISSUE THREAD

**Issue by MaxLiebe** [SuspiciousLookingOwl/youtubei#46]
**Describe the bug**
The getVideo() method currently returns undefined for every case (presumably due to a restructure in response data?)

**To Reproduce**
Use getVideo() in any way, even the example code breaks.

**Expected behavior**
A video containing the metadata is returned.

**Additional context**
I was able to fix the issue myself by just removing all the [3]s and [2]s after 'data' in every relevant file. Seems to work fine now.

**Comment by SuspiciousLookingOwl** [comment]
Fixed in `0.0.1-rc.34`
