### ISSUE TITLE
[ENHANCEMENT]  Result finding improvement 

### ISSUE THREAD

**Issue by MontiKasta** [SuspiciousLookingOwl/youtubei#48]
**Is your feature request related to a problem? Please describe.**
When you click share a video button on Youtube, it gives you a link with `?feature=share` at the end (usually in shorts videos). This is normal, but if you type this link in the search field, it says "no results found". If you remove the `?feature=share` part from the link, it will give you the result you want at the top.

**Describe alternatives you've considered**
I think every developer can solve this problem very easily. For example :

```javascript
const link = "https://www.youtube.com/watch?v=dQw4w9WgXcQ?feature=share"
link.replace("?feature=share",'')
```

**_I thought it would be better if the module did this automatically._**

**Comment by SuspiciousLookingOwl** [comment]
I tried
```js
const [video] = await youtube.search("https://www.youtube.com/watch?v=dQw4w9WgXcQ?feature=share");
console.log(video)
```
and it gives me the [correct video](https://www.youtube.com/watch?v=dQw4w9WgXcQ), I don't know why it doesn't show the correct result for you.

Either way, I think altering the search keyword from library side is not a good idea, what the developer pass on the params should be what the library pass to Youtube

**Comment by MontiKasta** [comment]
This is just an example link. I wanted to show an example of the code. If you try it on a youtube shorts video you'll know what I mean.

For example : https://youtube.com/shorts/vgubcsrkmzA?feature=share

**Comment by SuspiciousLookingOwl** [comment]
Ahh I see what you mean, this issue is more about adding URL support in `.getVideo()` for Youtube Shorts, not query params, because both:
```js
await youtube.getVideo("https://youtube.com/shorts/vgubcsrkmzA?feature=share");
await youtube.getVideo("https://youtube.com/shorts/vgubcsrkmzA");
```
won't work.

I will add this soon as well as YouTube shorten URL (`https://youtu.be/{id}`)

**Comment by MontiKasta** [comment]
I got an error in playlist searches but I couldn't find the reason.

I got an error on a Youtube playlist :

```javascript
await youtube.getPlaylist("https://www.youtube.com/playlist?list=RDCLAK5uy_m0X_CFV7sbR3EKDoP_FvqyK5faV7xorUY")
```


MixPlaylist.js:20 gives error :
TypeError: Cannot read properties of undefined (reading 'playlist')

**Comment by SuspiciousLookingOwl** [comment]
URL support will be removed in v1 https://github.com/SuspiciousLookingOwl/youtubei/pull/53/commits/46e4d89bf53ee7d3daf01121c7226c577aa71eca

You will have to create your own parser to extract playlist id or video id from a string / URL
