### ISSUE TITLE
Videos not available in topic channels

### ISSUE THREAD

**Issue by titong0** [SuspiciousLookingOwl/youtubei#58]
**Describe the bug**
The `channel.videos.items` property doesn't change after calling the  `channel.videos.items.next()` method.

**To Reproduce**
Get a topic channel's id like **UCRY5dYsbIN5TylSbd7gVnZg**
```javascript
const channelInfo = await youtube.getChannel(channelId);

console.log(channelInfo?.videos.items); // []
await channelInfo?.videos.next();
console.log(channelInfo?.videos.items); // still []
```
**Expected behavior**
`console.log(channelInfo?.videos.items);` should log videos' information

**Comment by SuspiciousLookingOwl** [comment]
Seems like this is expected? Unlike other channel, this channel doesn't have `Videos` tab
![image](https://user-images.githubusercontent.com/32597776/183321647-34b5acce-8631-4467-b16b-da3673bbe7a8.png)
![image](https://user-images.githubusercontent.com/32597776/183321632-a2d044ec-c94d-4a33-80d4-1f94cc99493d.png)

**Comment by titong0** [comment]
Hello, I didn't know the `channelInfo.videos.items` property was for links under the videos tab, this clarifies it. Is there any way to get the videos then? or a safe way to know wether it is a topic channel in order to check playlists?

I've found all topic channels have `videoCount = 0`, `suscriberCount = undefined` and, if the channel belongs to an artist, a prop thats something like:
```javascript
shelves: [
    { title: 'Albums & Singles', subtitle: undefined, items: [Array] }
  ]
```
also, in  `https://www.youtube.com/channel/{ID}/about` there is a link that says `"Auto-generated by YouTube"`. I'm not sure if this info helps

**Comment by SuspiciousLookingOwl** [comment]
I might be wrong, but seems like topic / auto-generated channel doesn't have videos, instead they only have playlists, the `Kanye West - Topic` channel have `All Tracks - Ye` playlist, so maybe you can get the video list from there.
```js
const channel = await c.getChannel("UCRY5dYsbIN5TylSbd7gVnZg");
if (!channel) return;

// get the "All Tracks" playlist
const [playlistCompact] = await channel.playlists.next();
// get full playlist object since playlist compact can't be used to load its videos
const playlist = await playlistCompact.getPlaylist();
// load all videos on playlist
await playlist.videos.next(0);

console.log(playlist.videos.items); // all videos inside "All Tracks" playlist
```
or simply
```js
const playlist = await c.getPlaylist("PLXu_cA-xfxWvzevttYDogR90P8z5wcyVc"); // playlist id of "All Tracks"
if (!(playlist instanceof Playlist)) return;

// load all videos on playlist
await playlist.videos.next(0);

console.log(playlist.videos.items); // all videos inside "All Tracks" playlist
```

**Comment by titong0** [comment]
The "All tracks" playlist doesn't actually have every single song for some reason, I still got this code to do what I wanted though. 

```javascript
const topicChannelAlbums = async (channelInfo: Channel) => {
  const albums = channelInfo.shelves.find(
    (i) => i.title === "Albums & Singles"
  );
  if (!albums) throw new Error("Could not find Albums & Singles shelf");

  return Promise.all(
    albums?.items.map(async (album) => {
      if (!(album instanceof PlaylistCompact)) return;
      const playlist = await album.getPlaylist();
      return {
        title: album.title,
        id: album.id,
        trackCount: album.videoCount,
        thumbnails: album.thumbnails,
        playlist,
      };
    })
  );
};
```

PS: do you think this could be useful for the docs?
