### ISSUE TITLE
[ENHANCEMENT] Workaround for Video Upload Date

### ISSUE THREAD

**Issue by rafaeljustinox** [SuspiciousLookingOwl/youtubei#7]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you would like***
Hi, I am using this package in my project and made a simple workaround to get the video upload date in Javascript Date format.
It's not ideal, but it can replace the current text.

I made a simple example using axios. I set the default language English in the request to get only date and time text in English.
After that, a function extracts the time from the text and converts it to the Date object.

https://gist.github.com/rafaeljustinox/620a0950c1e952c7ca4587aef0ba21ea

It is just an idea that works for me because I only need the date, but when the text allows, I convert to hours and minutes as well.

**Comment by SuspiciousLookingOwl** [comment]
This is a good idea! I will probably add this. I still need to check what are the drawbacks.

**Comment by SuspiciousLookingOwl** [comment]
I decided to leave the `uploadDate` as is and let the user parse the date if needed, mostly because the parsed result is inconsistent and I don't really like it, and this also allows the user to translate the `uploadDate` to any language they want if needed.
