### ISSUE TITLE
client.getVideo() - cannot read properties of undefined

### ISSUE THREAD

**Issue by baskwo** [SuspiciousLookingOwl/youtubei#71]
**Describe the bug**
When using getVideo we have an error

**To Reproduce**
Use for example this code

```
const { Client } = require("youtubei");

const youtube = new Client();

(async () => {
    const result = await youtube.getVideo("8acBQRAstNk");
    console.log(result);
})();
```

**Expected behavior**
Should return information about the video

**Screenshots**
![image](https://user-images.githubusercontent.com/2609621/210490338-3bef4456-4412-4743-856d-5044aa82f68f.png)

**Additional context**
It seems to be cause by a recent change from Youtube. Was working fine few days ago.

**Comment by SuspiciousLookingOwl** [comment]
Thank you for reporting the bug, should be fixed on `1.0.0` 🙂
