### ISSUE TITLE
Are there any rate limit using this library? 

### ISSUE THREAD

**Issue by chungquantin** [SuspiciousLookingOwl/youtubei#76]
What happen if I fetch 1000000 videos info from the channel? Are there any limited?

**Comment by SuspiciousLookingOwl** [comment]
I never tested for the actual limit, so I can't say for sure.

> Never get IP banned. I'm not sure about rate limit, because the response is a bit inconsistent, for example in 100 request you can get 1 fail request and need to resend the request, haven't dig into what causes this yet, might be the rate limiter, or just my library being buggy (e.g. not parsing the correct thing). I never tried to send a massive amount of requests though (in parallel for example), the most I've ever done is about 150 request / mins continuously for 15-20minutes in scrape-yt, and never received any bans from Youtube, haven't tried the same in youtubei but I expect the same thing.

That's the most that I've done, but that was 2 years ago, I don't know if anything changes (taken from https://github.com/SuspiciousLookingOwl/youtubei/issues/2)

Hope that helps!
