### ISSUE TITLE
getVideo() API throws `Converting circular structure to JSON...`

### ISSUE THREAD

**Issue by chungquantin** [SuspiciousLookingOwl/youtubei#77]
**Describe the bug**
Got this bug thrown when try to get the Video info using `getVideo` API.
```
Converting circular structure to JSON\n    --> starting at object with constructor 'BaseChannel'\n    |     property 'videos' -> object with constructor 'ChannelVideos'\n    --- property 'channel' closes the circle 
```
**To Reproduce**
Steps to reproduce the behavior: Using `getVideo()` and `youtubei: "^1.1.2"`
**Context**
Return Video class from express controller method

**Comment by SuspiciousLookingOwl** [comment]
Are you sure you are not doing `JSON.stringify()` somewhere on your code?

I just tested this code
```ts
const video = await client.getVideo("dQw4w9WgXcQ");
console.log(video);
```
and it works just fine

**Comment by chungquantin** [comment]
I solved this problem on my end by avoid picking circular type. I think this is an error caused by the non-serialized return type. Thank you anyway.
