### ISSUE TITLE
A way to set how many videos it loads at once.

### ISSUE THREAD

**Issue by AmNobCop** [SuspiciousLookingOwl/youtubei#79]
**Is your feature request related to a problem? Please describe.**
I am trying to use autocomplete but I can only show 25 options at a time and it always errors as the bot always gets more then 25 videos.

**Describe the solution you'd like**
A way to set how many videos it will search for at a time

**Comment by SuspiciousLookingOwl** [comment]
I think this is not possible as Youtube search page itself doesn't allow you to change how many results it fetches.
You have to assume that the search result count is always dynamic (from testing, it's usually between 18-20 results per fetch).
