### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FU510N-429** [SuspiciousLookingOwl/youtubei#8]
**Describe the bug**
When searching for certain songs ("bandit" for example) it comes back without any results.

**To Reproduce**
^

**Expected behavior**
I expected it to pull up a result

**Screenshots**

**Additional context**

**Comment by SuspiciousLookingOwl** [comment]
Can't reproduce with this code:

```ts
const youtube = new Client();

const run = async () => {
	const result = await youtube.search("bandit", { type: "video" });
	console.log(result.map((r) => r.title));
};

run();

```

Output:
![image](https://user-images.githubusercontent.com/32597776/112080840-3d606100-8bb5-11eb-8b13-d3624d007d35.png)

Can you share your code?
