### ISSUE TITLE
youtube.search function doesn't work in production

### ISSUE THREAD

**Issue by doronli** [SuspiciousLookingOwl/youtubei#80]
**Describe the bug**
The youtube.search(name) - [link](https://suspiciouslookingowl.github.io/youtubei/docs/youtube/classes/SearchResult) function work locally, but when I push the code to production I received a 500 status code error.

**To Reproduce**
upload youtube.search(name) function to production

**Expected behavior**
Received the same result as locally

**Screenshots**
<img width="1025" alt="image" src="https://github.com/SuspiciousLookingOwl/youtubei/assets/38883428/c7217617-c10c-4e03-85c6-d70a9539b653">

**Comment by ItsAnoch** [comment]
Has it been resolved yet?

**Comment by SuspiciousLookingOwl** [comment]
I can't really reproduce this issue unfortunately, I've tried running this on my VPS and when I'm using a VPN, both works fine.
