### ISSUE TITLE
Add "don't recommend channel"

### ISSUE THREAD

**Issue by ddsol** [SuspiciousLookingOwl/youtubei#88]
The videos in YouTube's "watch next" section are missing the "don't recommend channel" option. It would be great if this API would add this option to either the video or the channel.

YouTube has a tendency to recommend certain channels only in the "watch next" section and never in the main page, where the option "don't recommend channel" is available.

This API could allow blocking recommendations from these channels. It would be great to get rid of them once and for all. Clicking "not interested" has no effect to stop the channels from being recommended in "watch next", sometimes a dozen videos at a time.

**Comment by SuspiciousLookingOwl** [comment]
Probably not going to implement this. The "Don't recommend channel" feature on YouTube is only accessible for logged in users, something that is not implemented on this library (you can only fetch data as a guest / non logged in users with this library), and I'm not planning to add such feature anytime soon.
