### ISSUE TITLE
Cannot read properties of undefined (reading 'transcriptBodyRenderer') 

### ISSUE THREAD

**Issue by jenny4711** [SuspiciousLookingOwl/youtubei#95]
**Describe the bug**
It worked well until yesterday.
i have tried  few minutes ago, It comes to error as blow
Cannot read properties of undefined (reading 'transcriptBodyRenderer') 
Please fix for this issue
![Screenshot 2024-04-05 at 9 21 54 PM](https://github.com/SuspiciousLookingOwl/youtubei/assets/57854947/b882ad8f-bd02-44fb-b83d-73ed38bcd27c)

**Comment by SuspiciousLookingOwl** [comment]
It seems like they changed the API for getting the video transcript, I'll get this fixed soon.

**Comment by jenny4711** [comment]
OK. Thank you. I will wait!

**Comment by jenny4711** [comment]
When you fix it, Please Let me know. ^^
Thank You

2024년 4월 5일 (금) 오후 11:25, SuspiOwl ***@***.***>님이 작성:

**Comment by SuspiciousLookingOwl** [comment]
Fixed on `1.4.0`, please update your version.

I also added more complete support for captions
```js
const video = client.getVideo("...");

// printing out available languages (and its code) for captions
console.log(video.captions.languages.map((l) => `${l.code} - ${l.name}`)); 

// printing out captions of a specific language using language code
console.log(await result.captions.get("en")); 
```

**Comment by jenny4711** [comment]
Hello~ Thank you.
but I tried that you show the code, it did not work well!
installed 1.4.0 but didn't work. Can you Please what is wrong this code?
[image: Screenshot 2024-04-06 at 6.22.47 PM.png]

[image: Screenshot 2024-04-06 at 6.24.04 PM.png]

2024년 4월 6일 (토) 오후 2:50, SuspiOwl ***@***.***>님이 작성:

**Comment by jenny4711** [comment]
Thank You so much . Now is working!
